[config]
schemaVersion = "0.0.1"


[package]
namespace = "erumi321"
name = "Blind_Accessibility"
versionNumber = "0.1.1"
description = "Adds a lot of Blind Accessibility features into the game, and overhauls a lot of menus. Heavily recommended to have TOLk Compatability mod"
websiteUrl = "https://github.com/erumi321/Hades2BlindAccessibility"
containsNsfwContent = false

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.28"
SGG_Modding-ENVY = "1.0.1"
SGG_Modding-Chalk = "2.1.1"
SGG_Modding-ReLoad = "1.0.1"
SGG_Modding-SJSON = "1.0.0"
SGG_Modding-ModUtil = "3.1.1"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"


[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "Mods"]
